let score = 0;
let currentQuestion = 0;
let quizQuestions = [
    {
      text: 'What is the Bible verse Jules Winnfield likes to recite in "Pulp Fiction" ?',
      choices: ['Genesis 3:8', '1 Thessalonians 5:11', 'Ezekiel 25:17', 'Ezra 9:9'],
      correctChoice: 2
    },

    {
      text: `In "Formula 51", what is Elmo McElroy's signature piece of clothing:`,
      choices: ['a kilt','an ascot', 'knee high socks', 'nothing - Elmo prefers nudity'],
      correctAnswer: 0
    }
]

    
/////EVENT HANDLERS/////////////////////////
//// attached to 'Begin' button in Start View////

function beginQuiz() {
    $('#begin').click(function(event) {
        event.preventDefault();
        showQuestion();     
      })
}


////attached to Submit-Answer button in Quiz View////
$('#submit-answer').click(function(event) {
    event.preventDefault();
    var guess = $('input:checked').val();
    console.log(`guess = ${guess}`);
    
    let question = quizQuestions[currentQuestion];  
    let correctAnswer = question.correctChoice;
    console.log(`correctAnswer = ${correctAnswer}`);
    if (guess == correctAnswer) {
        score++;
        //console.log(`score = ${score}`);
        //alert("CORRECT");
        $(rightAnswerView);
    } else {
        //console.log(`score = ${score}`);
        //alert("WRONG");
        $(wrongAnswerView);
    }
});

/*Event handler generated by Right/Wrong Answer view: increment currentQuestion
                                                      hide answer view
                                                      show quiz view updated with current question*/
function continueQuiz() {
    $('#continue-quiz').click(function(event) {
       event.preventDefault();
       $('answer').hide();
       currentQuestion++;
       //console.log(`currentQuestion = ${currentQuestion}`);
       showQuestion();
  })
}

/*$('#restart-quiz').click(function(event) {
    $('.results').hide();
    $('.quiz').show();
    score = 0;
    currentQuestion = 0;
    showQuestion();
  });*/

////////////////////////////////////////////////  

function showQuestion() {
    $('.start').hide();
    $('.quiz').show();

    let question = quizQuestions[currentQuestion];
    console.log(question.text);
    $('.quiz h2').text(question.text);
    $('.quiz form').html('');
    for (var i = 0; i < question.choices.length; i ++) {
        $('.quiz form').append(`<input type="radio" name="choice" value="${i}" checked>${question.choices[i]}<br>`);   
    };
    $('#question-counter').text(`Question ${currentQuestion + 1}`);
    $('#score-counter').text(`Score: ${score} out of ${quizQuestions.length}`);
    
}

/*rightAnswerView: increments score by 1
                   hides the quiz view 
                   shows the view for a correct answer
                   shows the button to continue which is handled by event listener*/
function rightAnswerView() {
    score++;
    $('.quiz').hide();
    //$('answer').html('');
    $('.answer').append(
        `
           <h2>CORRECTAMUNDO!</h2>
           <img src="https://pbs.twimg.com/media/C0PbBJfVEAEPuyY.jpg" alt="Sam Happy">
           <button id="continue-quiz">continue</button>
        `      
        );
    $('.answer').show();
    continueQuiz();
}

/*wrongAnswerView: hides quiz view
                   shows wrong answer view (including the actual correct answer)
                   shows continue quiz button which is handled by event listener*/
function wrongAnswerView(){
    let question = quizQuestions[currentQuestion];
    let actualAnswer = question.correctAnswer;
    $('.quiz').hide();
    $('answer').html('');
    $('.answer').append( 
        `
           <h2>I'M SORRY DID I BREAK YOUR CONCENTRATION?</h2>
           <img src="http://www.premcast.com/wp-content/uploads/2015/09/Samuel-L-Jackson-Bedtime-300x150.jpg" alt="Sam Angry">
           <p>The correct answer is ${question.choices[actualAnswer]}</p>
           <button id="continue-quiz">continue</button>
       `
    );
    
    $('.answer').show();
    continueQuiz();
}

function handleSamQuiz() {
    beginQuiz();
    //submitAnswer();
}

$(handleSamQuiz);









/*function verifyGuess(guess) {
    $('#submit-answer').click(function(event) {
        event.preventDefault();
        var guess = $('input:checked').val();
        console.log(`guess = ${guess}`);
      
        let question = quizQuestions[currentQuestion];
        console.log(`correctAnswer = ${question.correctAnswer}`);
        console.log(question);
        if (guess == question.correctAnswer) {
            score++;
            console.log(`score = ${score}`);
            rightAnswerView();
        } else {
           // wrongAnswerView();
        };
      
        currentQuestion++;
        console.log(`currentQuestion = ${currentQuestion}`)
      
        if (currentQuestion === quizQuestions.length) {
            finalResults();
        } else {
            showQuestion();
        }
      });
}*/

/*function rightAnswerView() {
   $('.quiz').hide();
   $('.right-answer').show();
   
   $('#right-continue-quiz').click(function(event) {
     event.preventDefault();
     $('.right-answer').hide();
     $('.quiz').show();
   })

}

/*function wrongAnswerView() {
   let question = quizQuestions[currentQuestion];
   let actualAnswer = question.correctAnswer;
   The correct answer is ${question.choices[actualAnswer]}
   console.log(actualAnswer);
   $('.quiz').hide();
   $('#actual').text(`The correct answer is ${question.choices[actualAnswer]}`);   
   $('.wrong-answer').show();

   $('#wrong-continue-quiz').click(function(event) {
    event.preventDefault();
    $('.wrong-answer').hide();
    $('.quiz').show();
  });

};*/


/*function finalResults() {
  $('.quiz').hide();
  $('.right-answer').hide();
  $('.wrong-answer').hide();
  $('.results').show();
  $('.results p').text("Final Score: " + score + " out of " + quizQuestions.length + "!")

  $('#restart-quiz').click(function(event) {
    $('.results').hide();
    $('.quiz').show();
    score = 0;
    currentQuestion = 0;
    showQuestion();
  });
}*/
